name: Generate snake animation
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: svvoii
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
      - name: Check out output branch
        run: |
          git fetch
          git checkout output
          git pull
      - name: Copy SVG to output branch
        run: cp dist/github-contribution-grid-snake.svg .
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add github-contribution-grid-snake.svg
          git commit -m "Update GitHub contribution grid snake animation"
          git push